name: java-build job using GH action

on:
  push:
    branches:
      - stage

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - name: maven version
        run: mvn --version
      - name: building jar
        run: mvn clean package
      - name: check path
        run: |
          echo $PWD
      - name: upload jar
        uses: actions/upload-artifact@v4
        with:
          name: war-artifact
          path: target/*.war
  SAST_SCAN:
    env:
      SONAR_HOST_URL: http://ec2-54-89-220-216.compute-1.amazonaws.com:9000
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5.2.0 # Ex: v4.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
        sonar.projectkey: "maven-web-application"